version: '3.9'

services:
  psql-dev:
    image: postgres
    container_name: psql-dev
    restart: always
    ports:
      - ${POSTGRES_PORT_PC}:${POSTGRES_PORT_CONTAINER}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT_CONTAINER}
    ports: 
      - ${PGADMIN_LISTEN_PORT_PC}:${PGADMIN_LISTEN_PORT_CONTAINER}